In [1]:
import torch
import torch.nn as nn

In [2]:
pred = torch.randn(4, 5)
label = torch.randn(4, 5)


# MSE

In [8]:
mse = nn.MSELoss(reduction='none')
loss = mse(pred, label)
loss

tensor([[5.6797e-02, 2.1835e-03, 1.0304e+00, 1.1968e+00, 7.5716e+00],
        [5.7056e-01, 7.9701e-01, 2.0344e+00, 1.3452e+00, 4.0305e-01],
        [2.8356e+00, 7.7713e+00, 1.1675e-01, 2.7761e+00, 7.3770e-02],
        [1.2051e+00, 5.2801e+00, 2.6771e+00, 8.8406e+00, 2.4521e-01]])

In [9]:
mse = nn.MSELoss(reduction='mean')
loss = mse(pred, label)
loss

tensor(2.3415)

In [10]:
mse = nn.MSELoss(reduction='sum')
loss = mse(pred, label)
loss

tensor(46.8296)

In [11]:
((pred - label)**2).mean()

tensor(2.3415)

# BCE

In [12]:
pred

tensor([[ 0.4436, -0.7254,  1.9803, -0.9308, -1.4758],
        [ 1.8714, -0.2413,  0.5381,  1.5797,  0.2050],
        [-1.4760,  1.1556,  0.4570, -2.2494,  0.2202],
        [ 0.3368, -1.9509, -0.1865,  1.0884,  0.0310]])

In [13]:
label = torch.zeros(4, 5).random_(0,  2)
label

tensor([[1., 1., 0., 0., 0.],
        [1., 0., 0., 0., 1.],
        [0., 1., 0., 1., 1.],
        [1., 0., 0., 1., 1.]])

In [14]:
sigmoid = nn.Sigmoid()

In [15]:
bce = nn.BCELoss(reduction='none')
bce(sigmoid(pred), label)

tensor([[0.4958, 1.1202, 2.1096, 0.3323, 0.2059],
        [0.1431, 0.5798, 0.9979, 1.7670, 0.5959],
        [0.2058, 0.2737, 0.9475, 2.3497, 0.5891],
        [0.5389, 0.1329, 0.6042, 0.2902, 0.6778]])

In [16]:
bce = nn.BCELoss(reduction='mean')
bce(sigmoid(pred), label)

tensor(0.7479)

In [17]:
bce = nn.BCELoss(reduction='sum')
bce(sigmoid(pred), label)

tensor(14.9574)

#BCE with Logits

In [20]:
bcel = nn.BCEWithLogitsLoss(reduction='none')
bcel(pred, label)

tensor([[0.4958, 1.1202, 2.1096, 0.3323, 0.2059],
        [0.1431, 0.5798, 0.9979, 1.7670, 0.5959],
        [0.2058, 0.2737, 0.9475, 2.3497, 0.5891],
        [0.5388, 0.1329, 0.6042, 0.2902, 0.6778]])

In [19]:
bcel = nn.BCEWithLogitsLoss(reduction='mean')
bcel(pred, label)

tensor(0.7479)

In [21]:
bcel = nn.BCEWithLogitsLoss(reduction='sum')
bcel(pred, label)

tensor(14.9574)

In [22]:
import numpy as np
x = pred.numpy()
y = label.numpy()


In [23]:
loss_vals = []
for i in range(len(y)):
  batch_loss = []
  for j in range(len(y[i])):
    if y[i][j] == 1:
      loss = -np.log(x[i][j])
    else:
      loss = -np.log(1 - x[i][j])
    batch_loss.append(loss)
  loss_vals.append(batch_loss)



<ipython-input-23-307d17cd887e>:6: RuntimeWarning: invalid value encountered in log
  loss = -np.log(x[i][j])
<ipython-input-23-307d17cd887e>:8: RuntimeWarning: invalid value encountered in log
  loss = -np.log(1 - x[i][j])


In [26]:
#sigmoid
def sigmoid(x):
  return 1 / (1 + np.exp(-x))
x = sigmoid(x)

In [27]:
loss_vals = []
for i in range(len(y)):
  batch_loss = []
  for j in range(len(y[i])):
    batch_loss.append(-np.log(x[i][j]) if y[i][j] == 1 else -np.log(1 - x[i][j]))
  loss_vals.append(batch_loss)



In [28]:
loss_vals

[[0.49575162,
  1.1202195,
  2.1096237500592703,
  0.3323388996373558,
  0.20588079597690023],
 [0.14314857,
  0.5797618681862735,
  0.9979316336885763,
  1.7670447828099398,
  0.59588236],
 [0.2058349363224285, 0.27372843, 0.9475239944076592, 2.349671, 0.58909094],
 [0.53885, 0.13291276858977627, 0.6042275201542165, 0.29024115, 0.67778313]]

In [29]:
np.mean(loss_vals)

0.747872375967572