In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

# Word Embeddings

In [3]:
# Indices of the words represent the values in the lookup table
word_to_idx = {"I": 0, "love": 1, "eating": 2, "and": 3, "sleeping": 4}
embeddings = nn.Embedding(5, 7) # 5 words in vocab, embedding size is 7

In [4]:
embeddings

Embedding(5, 7)

In [5]:
word_index = torch.tensor([word_to_idx["love"]])
print(word_index)

tensor([1])


In [6]:
love = embeddings(word_index)
print(love)
print(love.shape)

tensor([[-0.4719,  0.2832, -0.6562,  0.1406, -0.5921,  0.4537, -0.7931]],
       grad_fn=<EmbeddingBackward0>)
torch.Size([1, 7])


In [7]:
all_ind = torch.tensor([w for w in range(5)], dtype=torch.long)
all_words = embeddings(all_ind)
print(all_ind)

tensor([0, 1, 2, 3, 4])


In [8]:
all_words

tensor([[-0.6644, -0.1390,  1.2543,  0.1611, -0.0954,  0.2156, -1.3369],
        [-0.4719,  0.2832, -0.6562,  0.1406, -0.5921,  0.4537, -0.7931],
        [ 0.5788,  0.8581,  0.9345, -0.5230, -0.7533,  0.8847,  1.1803],
        [ 1.2384,  1.2869, -0.6303, -0.1922,  0.5432,  0.5434, -0.4856],
        [ 0.2903,  0.2078, -0.2984,  0.1410,  1.1548, -2.3594, -0.6751]],
       grad_fn=<EmbeddingBackward0>)

In [9]:
all_words.shape

torch.Size([5, 7])