In [1]:
import torch
import numpy as np

In [2]:
v = torch.tensor([1,2,3])
print(v,type(v),v.type())

tensor([1, 2, 3]) <class 'torch.Tensor'> torch.LongTensor


In [4]:
v = torch.FloatTensor([1,2,3])
print(v,v.type())

tensor([1., 2., 3.]) torch.FloatTensor


In [5]:
v = torch.tensor([1,2,3,4,5,6])
print(v,type(v),v.type())

tensor([1, 2, 3, 4, 5, 6]) <class 'torch.Tensor'> torch.LongTensor


In [7]:
print(v.view(6,1))

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


In [8]:
print(v.view(3,-1))

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [11]:
a = np.array([1,2,3,4,5,6])
a,type(a)

(array([1, 2, 3, 4, 5, 6]), numpy.ndarray)

In [13]:
b = torch.from_numpy(a)
b

tensor([1, 2, 3, 4, 5, 6], dtype=torch.int32)

In [14]:
b.type()

'torch.IntTensor'

In [15]:
c = b.numpy()
c

array([1, 2, 3, 4, 5, 6])

In [16]:
type(c)

numpy.ndarray