Lower the temperature higher the confidence

In [4]:
import torch
import torch.nn.functional as F

In [2]:
predictions = torch.log(torch.rand(3))

In [3]:
predictions

tensor([-1.2523, -0.2076, -1.3547])

In [5]:
F.softmax(predictions, dim=-1)

tensor([0.2107, 0.5990, 0.1902])

In [6]:
F.softmax(predictions / 0.5, dim=-1)

tensor([0.1011, 0.8166, 0.0823])

In [7]:
F.softmax(predictions / 0.1, dim=-1)

tensor([2.9031e-05, 9.9996e-01, 1.0428e-05])

In [8]:
F.softmax(predictions / 100, dim=-1)

tensor([0.3323, 0.3358, 0.3319])

In [9]:
F.softmax(predictions / 200, dim=-1)

tensor([0.3328, 0.3346, 0.3326])

In [10]:
F.softmax(predictions / 1000, dim=-1)

tensor([0.3332, 0.3336, 0.3332])

In [11]:
F.softmax(predictions / 10000, dim=-1)

tensor([0.3333, 0.3334, 0.3333])

In [12]:
F.softmax(predictions / 100000, dim=-1)

tensor([0.3333, 0.3333, 0.3333])

In [13]:
F.softmax(predictions / 1000000, dim=-1)

tensor([0.3333, 0.3333, 0.3333])