In [1]:
import torch

In [ ]:
# Concate tensors
# 1st dim must match
a = torch.randn(2,5)
b = torch.randn(3,5)
torch.cat([a, b]) # concate in 0th dim

tensor([[-0.5285,  1.4153,  0.5781,  0.3773, -0.0400],
        [-0.2050,  0.1239,  1.4207, -0.0517,  0.2380],
        [ 0.0761,  0.9751, -0.7347, -1.6289, -0.9823],
        [-0.5022, -0.0622, -0.1461, -2.4757,  0.7012],
        [-1.0570,  1.6021, -0.9512,  0.8665,  0.5940]])

In [ ]:
# the 0th dim must match
a = torch.randn(2, 3)
b = torch.randn(2, 5)
torch.cat([a, b], 1) # dim 1

tensor([[-0.4802, -1.9236,  0.1815, -0.1017,  0.8857,  0.8020, -0.8056, -2.7386],
        [-0.0875,  0.2226,  0.2308,  1.0279,  1.3120, -0.5585, -0.6863,  0.8723]])

In [ ]:
# Squeezing tensors
# adding dim to tensor

a = torch.tensor([1, 2, 3, 4])
b = torch.unsqueeze(a, 0)
b, b.shape

(tensor([[1, 2, 3, 4]]), torch.Size([1, 4]))

In [ ]:
c = torch.unsqueeze(a, 1)
c, c.size

(tensor([[1],
         [2],
         [3],
         [4]]),
 <function Tensor.size>)

In [ ]:
torch.rand(2, 3, 4) # 2 channel, 3 rows and 4 cols

tensor([[[0.3273, 0.3528, 0.9768, 0.1704],
         [0.0268, 0.0898, 0.8118, 0.8803],
         [0.3754, 0.9895, 0.8773, 0.7383]],

        [[0.8895, 0.6811, 0.7453, 0.2334],
         [0.7419, 0.7463, 0.5421, 0.2139],
         [0.6830, 0.5507, 0.8787, 0.1986]]])

# auto grad

In [ ]:
x = torch.tensor([1., 2., 3.], requires_grad=True)
y = torch.tensor([4., 5., 6.], requires_grad=True)
z = x+y
z

tensor([5., 7., 9.], grad_fn=<AddBackward0>)

In [ ]:
 z.grad_fn

In [ ]:
s = z.sum()
print(s, s.grad_fn)

tensor(21., grad_fn=<SumBackward0>) <SumBackward0 object at 0x7f0badc57a30>


In [ ]:
s.backward()

In [ ]:
x.grad

tensor([1., 1., 1.])

In [2]:

# requires_grad is False by default
x = torch.randn(2, 2)
y = torch.randn(2, 2)

In [3]:
x.requires_grad, y.requires_grad

(False, False)

In [4]:
z = x+y
z.grad_fn

In [5]:
x.requires_grad_()
y.requires_grad_()

tensor([[0.0945, 0.2132],
        [1.5578, 0.0389]], requires_grad=True)

In [6]:
z = x+y
z.grad_fn

In [7]:

new_z = z.detach()

In [8]:
new_z

tensor([[ 0.6358, -0.3053],
        [ 0.6811,  0.4807]])

In [9]:
new_z.grad_fn
