In [1]:
import torch
import torch.nn as nn

In [2]:
layer = nn.Linear(5, 5)
layer

Linear(in_features=5, out_features=5, bias=True)

In [3]:
layer.weight.data

tensor([[ 0.0201, -0.1455,  0.2003, -0.0947, -0.1478],
        [-0.1138,  0.3532, -0.4419,  0.2670, -0.1013],
        [ 0.2316, -0.1974,  0.2705,  0.0595, -0.2240],
        [-0.3636, -0.2650,  0.1836,  0.2927, -0.2942],
        [ 0.0881, -0.0978, -0.0393,  0.3286, -0.3709]])

In [4]:
nn.init.uniform_(layer.weight.data, a=0.0, b=3)

tensor([[0.1897, 0.2019, 2.6107, 1.7346, 1.7730],
        [1.5504, 2.8193, 2.2548, 0.3495, 0.3486],
        [1.0505, 2.2515, 1.5162, 1.4969, 0.2516],
        [2.9375, 0.1607, 1.2014, 2.1334, 1.0875],
        [0.1012, 1.6943, 1.9827, 1.8947, 0.8095]])

In [6]:
nn.init.normal_(layer.weight.data, mean=0, std=1)

tensor([[ 0.9142, -1.9620, -0.1572,  0.0709,  0.2727],
        [-0.5492,  2.4332,  0.9036,  0.5757,  0.3292],
        [ 0.2806, -2.5251,  0.1731, -3.4625, -0.2765],
        [-0.0279, -1.1452,  1.4690, -0.3441, -0.6207],
        [ 1.8857,  0.1695,  0.4767,  0.2545,  0.7425]])

In [8]:
nn.init.normal_(layer.weight, mean=0, std=0.2)

Parameter containing:
tensor([[ 0.3326, -0.4234, -0.2228,  0.0393,  0.0794],
        [-0.0380,  0.0549, -0.1479,  0.2082, -0.0178],
        [-0.0928, -0.0242,  0.0636,  0.0949, -0.3368],
        [ 0.2138,  0.0981,  0.2140, -0.3318, -0.0254],
        [ 0.2099, -0.0547, -0.0283, -0.0863, -0.1072]], requires_grad=True)

In [10]:
# wrong
nn.init.constant_(layer.weight, val=1)

Parameter containing:
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], requires_grad=True)

In [11]:
nn.init.constant_(layer.bias, val=1)

Parameter containing:
tensor([1., 1., 1., 1., 1.], requires_grad=True)

In [12]:
nn.init.xavier_uniform_(layer.weight, gain=1)

Parameter containing:
tensor([[-0.4207,  0.5362,  0.5030, -0.4215,  0.5552],
        [-0.2489,  0.4311,  0.2846,  0.3780, -0.1972],
        [-0.6081, -0.1792,  0.1426,  0.2433, -0.4526],
        [-0.4640,  0.3900, -0.7089, -0.5708, -0.2123],
        [ 0.3986, -0.2706,  0.4772,  0.2139,  0.4862]], requires_grad=True)

In [13]:
nn.init.xavier_normal_(layer.weight, gain=1)

Parameter containing:
tensor([[-2.7367e-02, -2.0168e-02,  3.3726e-01,  2.9218e-01, -2.6723e-01],
        [-3.6587e-01,  7.7042e-01, -1.8900e-01, -5.4310e-03, -1.5605e-01],
        [-4.2867e-01,  5.9381e-01,  2.4699e-01,  1.0307e-01, -3.1084e-01],
        [ 2.0514e-01, -2.5836e-01,  8.4867e-01,  6.1032e-04, -4.3372e-02],
        [ 1.0180e+00,  2.9358e-01, -3.3192e-01,  8.1084e-01, -3.6333e-01]],
       requires_grad=True)